### ISSUE TITLE
install by yay cause error: failed to run custom build command for `alpm v4.0.0`

### ISSUE THREAD

**Issue by debugbb** [Morganamilo/paru#1238]
yay -Su paru-git

choose rust

error: failed to run custom build command for `alpm v4.0.0`

Caused by:
  process didn't exit successfully: `/home/core/.cache/yay/paru-git/src/paru/target/release/build/alpm-54a2e904469445ec/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/core/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-4.0.0/build.rs:25:13:
  this version of alpm.rs does not support libalpm v14.0.0 only v15.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
==> 错误： 在 build() 中发生一个错误。
    正在放弃...
 -> 生成时出错: paru-git-exit status 4

**Comment by kitalia** [comment]
`RUST_BACKTRACE=1 CARGO_TARGET_DIR=/tmp/cargo-installsBLpar CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true cargo install paru`


```
error: failed to run custom build command for `alpm v2.2.3`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installsBLpar/release/build/alpm-b96d13ab06119510/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/alarm/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alpm-2.2.3/build.rs:25:13:
  this version of alpm.rs does not support libalpm v14.0.0 only v13.x.x is supported
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: build_script_build::main
               at ./build.rs:25:13
     3: core::ops::function::FnOnce::call_once
               at /build/rust/src/rustc-1.81.0-src/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```
![libalpm v14 0 0 only v13 x x is supported](https://github.com/user-attachments/assets/2e030a4b-ef9e-453b-9646-2d195828faac)

**Comment by kands-code** [comment]
> choose rust

Which version of Rust did you use to compile paru-git? I had no problems compiling with Rust Nightly.

```plaintext
Name            : paru-git
Version         : 2.0.3.rebuild.1.r1.g90656a9-1
Description     : Feature packed AUR helper
Architecture    : x86_64
URL             : https://github.com/morganamilo/paru
Licenses        : GPL-3.0-or-later
Groups          : None
Provides        : paru
Depends On      : git  pacman  libalpm.so>=14
Optional Deps   : bat: colored pkgbuild printing
                  devtools: build in chroot and downloading pkgbuilds
Required By     : None
Optional For    : None
Conflicts With  : paru
Replaces        : None
Installed Size  : 8.28 MiB
Packager        : Unknown Packager
Build Date      : 2024
Install Date    : 2024
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

@kitalia Currently stable versions, or tagged versions, cannot use libalpm v15.0.0, so if you want to use paru, please use paru-git or do not use the core-testing repo to upgrade pacman.

**Comment by kureta** [comment]
pacman is now upgraded on official repos and this brakes paru installation.

**Comment by ineu** [comment]
Here's the error of `makepkg`:
```
   Compiling async-compression v0.4.6
error: failed to run custom build command for `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)`

Caused by:
  process didn't exit successfully: `/tmp/tmp.ySDylO6Idj/paru/src/paru-2.0.3/target/release/build/alpm-1d3e607f04a83636/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/ineu/.cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/306342e/alpm/build.rs:25:13:
  this version of alpm.rs does not support libalpm v15.0.0 only v14.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by lautarovculic** [comment]
Same here

```bash
Compiling markup5ever v0.11.0
error: failed to run custom build command for `alpm v3.0.4 (https://github.com/archlinux/alpm.rs?rev=306342#306342ef)`

Caused by:
  process didn't exit successfully: `/home/lautaro/paru/src/paru-2.0.3/target/release/build/alpm-fe8130be9696cf00/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/lautaro/.cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/306342e/alpm/build.rs:25:13:
  this version of alpm.rs does not support libalpm v15.0.0 only v14.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by peterneutron** [comment]
As a crude hack you can just symlink `libalpm.so.14 -> libalpm.so.15.0.0` and continue using your existing `paru` installation. Note that there is also an error when using a kernel build without `landlock` -> `error: restricting filesystem access failed because landlock is not supported by the kernel!`

**Comment by debugbb** [comment]
@kands-code I installed it using yay and I don't see which version of Rust is being used.
