### ISSUE TITLE
paru hangs in command 'paru -Si pamac-aur'

### ISSUE THREAD

**Issue by manuel-192** [Morganamilo/paru#501]
### Affected Version
paru v1.8.1 - libalpm v13.0.0

### Description
paru hangs with option -Si for AUR packages. Looks like it is a language issue, because it works if I prefix the command with LANG=C:
```
paru -Si pamac-aur   # hangs (my default LANG is not English)
LANG=C paru -Si pamac-aur   # works
```
Hanging seems to occur between lines **Optional Deps** and **Conflicts With**.

**Comment by Morganamilo** [comment]
Then it may be useful to what lang your are using.

**Comment by lukasmichel** [comment]
I just experienced the hang in paru. It could well be a language issue. When running with my standard locale `LANGUAGE=de:de_DE`, paru hangs, if I change to `LANGUAGE=en`, it does not.
Furhtermore, it looks like some kind of infinite recursion or so, as paru occupied all my memory (I had to wait for the OOM-killer to kill the process).

I have also run paru in debug mode from (built from git head) with command `$ LANGUAGE=de RUST_BACKTRACE=full cargo run -- -Si paru`, which gave me the following trace

```
Finished dev [unoptimized + debuginfo] target(s) in 0.10s
Running `target/debug/paru -Si paru`
Repositorium         : aur
Name                 : paru
Version              : 1.8.1-1
Beschreibung         : Feature packed AUR helper
URL                  : https://github.com/morganamilo/paru
AUR URL              : https://aur.archlinux.org/packages/paru
Gruppen              : Keine
Lizenzen             : GPL3
Stellt bereit        : Keine
Abhängigkeiten       : git  pacman
Make-Abhängigkeiten  : cargo
Prüfe Abhängigkeiten : Keine
thread 'main' panicked at 'attempt to subtract with overflow', src/info.rs:162:17
stack backtrace:
   0:     0x559ba71dddc0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x559ba71dddc0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559ba71dddc0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x559ba71dddc0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x559ba7201c1f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x559ba71d6882 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x559ba71e05f5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x559ba71e05f5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x559ba71e05f5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x559ba71e00a3 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x559ba71e0bfd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x559ba71e0767 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:495:13
  12:     0x559ba71de27c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x559ba71e06f9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x559ba644a9c1 - core::panicking::panic_fmt::h2242888e8769cd33
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:     0x559ba644a90d - core::panicking::panic::h10ab123a4b13cc79
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:50:5
  16:     0x559ba68198b4 - paru::info::print_info::ha7da131a8eb37f53
                               at /home/lukas/Documents/paru/src/info.rs:162:17
  17:     0x559ba681920e - paru::info::print_list::hcda578369dd863fb
                               at /home/lukas/Documents/paru/src/info.rs:149:9
  18:     0x559ba6817118 - paru::info::print_aur_info::{{closure}}::hf1bbcbba0f2dc633
                               at /home/lukas/Documents/paru/src/info.rs:92:41
  19:     0x559ba6815844 - paru::info::print_aur_info::hc4177e0fe24b5ecb
                               at /home/lukas/Documents/paru/src/info.rs:113:9
  20:     0x559ba66542ba - paru::info::info::{{closure}}::he839121dcb607681
                               at /home/lukas/Documents/paru/src/info.rs:49:9
  21:     0x559ba65a0971 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h47c7a4ac7bbee8a2
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  22:     0x559ba65daa09 - paru::handle_sync::{{closure}}::h401ec2d1d2fce9bb
                               at /home/lukas/Documents/paru/src/lib.rs:257:9
  23:     0x559ba65a3451 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb54e6d5e4ff91e0a
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  24:     0x559ba65d806e - paru::handle_cmd::{{closure}}::h9b15dcf264e2f6f0
                               at /home/lukas/Documents/paru/src/lib.rs:166:21
  25:     0x559ba65a0171 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h2ac92eb7ffa57492
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  26:     0x559ba65ddb10 - paru::run2::{{closure}}::hd5446405f2b1affa
                               at /home/lukas/Documents/paru/src/lib.rs:152:5
  27:     0x559ba65a1b31 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6fea07264bcb8b90
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  28:     0x559ba65dccb2 - paru::run::{{closure}}::h5f5970f2b99ba766
                               at /home/lukas/Documents/paru/src/lib.rs:130:11
  29:     0x559ba65a2769 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9353e1e932ec0df9
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  30:     0x559ba65e9490 - paru::main::{{closure}}::he94b9483bfafbff0
                               at /home/lukas/Documents/paru/src/main.rs:7:15
  31:     0x559ba65a3d7b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd44e8b955d3dc772
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  32:     0x559ba654e020 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h288b935634407d43
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/park/thread.rs:263:54
  33:     0x559ba65e3fec - tokio::coop::with_budget::{{closure}}::hff125d1e4d3ea45c
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:106:9
  34:     0x559ba64d37bc - std::thread::local::LocalKey<T>::try_with::ha1864e84ba68abb2
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  35:     0x559ba64d335d - std::thread::local::LocalKey<T>::with::ha58f8c395d822731
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  36:     0x559ba654d97c - tokio::coop::with_budget::h747c8108b2985fbc
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:99:5
  37:     0x559ba654d97c - tokio::coop::budget::h6f74894b78db663e
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:76:5
  38:     0x559ba654d97c - tokio::park::thread::CachedParkThread::block_on::h465d36b48bb2b922
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/park/thread.rs:263:31
  39:     0x559ba64e1d99 - tokio::runtime::enter::Enter::block_on::hda28006a4bbbc9bb
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/enter.rs:151:13
  40:     0x559ba659b5ee - tokio::runtime::thread_pool::ThreadPool::block_on::h67f5394b9955484e
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/thread_pool/mod.rs:71:9
  41:     0x559ba65e4149 - tokio::runtime::Runtime::block_on::h60b82e0ef74a121a
                               at /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/mod.rs:452:43
  42:     0x559ba65e92e4 - paru::main::h2368b3644d9c1e0c
                               at /home/lukas/Documents/paru/src/main.rs:8:5
  43:     0x559ba649b32b - core::ops::function::FnOnce::call_once::h9137b08e03dc60e9
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  44:     0x559ba64e688e - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c646bbf97e56ed6
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  45:     0x559ba65c65a1 - std::rt::lang_start::{{closure}}::h6ca887706a06d62c
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  46:     0x559ba71e10fa - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  47:     0x559ba71e10fa - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  48:     0x559ba71e10fa - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  49:     0x559ba71e10fa - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  50:     0x559ba71e10fa - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  51:     0x559ba65c6580 - std::rt::lang_start::h486e8bfca6414fb5
                               at /home/lukas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  52:     0x559ba65e95fc - main
  53:     0x7fedc9775b25 - __libc_start_main
  54:     0x559ba644b0ce - _start
  55:                0x0 - <unknown>
```
For `LANGUAGE=en`, no error occurs:
```
$ LANGUAGE=en RUST_BACKTRACE=full cargo run -- -Si paru
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/paru -Si paru`
Repository      : aur
Name            : paru
Version         : 1.8.1-1
Description     : Feature packed AUR helper
URL             : https://github.com/morganamilo/paru
AUR URL         : https://aur.archlinux.org/packages/paru
Groups          : None
Licenses        : GPL3
Provides        : None
Depends On      : git  pacman
Make Deps       : cargo
Check Deps      : None
Optional Deps   : asp  bat  devtools
Conflicts With  : None
Maintainer      : Morganamilo
Votes           : 291
Popularity      : 49.511485
First Submitted : Mon, 19 Oct 2020 00:43:50 +0000
Last Modified   : Fri, 13 Aug 2021 12:52:02 +0000
Out Of Date     : No
```

**Comment by manuel-192** [comment]
Sorry, I totally forgot to answer.
LANG is fi_FI-UTF-8.
