### ISSUE TITLE
Fails to build with pacman-git (failed to run custom build command for `alpm-sys v1.1.1`)

### ISSUE THREAD

**Issue by kattjevfel** [Morganamilo/paru#79]
```
error: failed to run custom build command for `alpm-sys v1.1.1`

Caused by:
  process didn't exit successfully: `/home/katt/build/makepkg/pkgbuilds/paru-git/src/paru/target/release/build/alpm-sys-d24e55605284fbaf/build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=alpm

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/katt/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.55.1/src/lib.rs:1896:31
  stack backtrace:
     0:     0x55d3d34a3f30 - std::backtrace_rs::backtrace::libunwind::trace::ha31cb35ba35052ca
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
     1:     0x55d3d34a3f30 - std::backtrace_rs::backtrace::trace_unsynchronized::h914154c46fedb791
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66
     2:     0x55d3d34a3f30 - std::sys_common::backtrace::_print_fmt::h4bed7544cf4783cc
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:79
     3:     0x55d3d34a3f30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h71baf994de642464
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:58
     4:     0x55d3d34c930c - core::fmt::write::hcb5569f97eae5185
                                 at /build/rust/src/rustc-1.47.0-src/library/core/src/fmt/mod.rs:1082
     5:     0x55d3d34a0947 - std::io::Write::write_fmt::hec04380539c975a7
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/io/mod.rs:1514
     6:     0x55d3d34a6450 - std::sys_common::backtrace::_print::h7217f428d769d34f
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:61
     7:     0x55d3d34a6450 - std::sys_common::backtrace::print::heb9b7db110cef504
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:48
     8:     0x55d3d34a6450 - std::panicking::default_hook::{{closure}}::hc8bd48d88d5fcceb
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:200
     9:     0x55d3d34a619c - std::panicking::default_hook::h4a7994bce6af5114
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:219
    10:     0x55d3d34a6ab3 - std::panicking::rust_panic_with_hook::h796dceade986353b
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:569
    11:     0x55d3d34a6689 - std::panicking::begin_panic_handler::{{closure}}::h04c1f5fa60189361
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:476
    12:     0x55d3d34a439c - std::sys_common::backtrace::__rust_end_short_backtrace::h1aa5b888ed842ec3
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:153
    13:     0x55d3d34a6649 - rust_begin_unwind
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:475
    14:     0x55d3d34c78c1 - core::panicking::panic_fmt::ha5b47339211aa855
                                 at /build/rust/src/rustc-1.47.0-src/library/core/src/panicking.rs:85
    15:     0x55d3d34c76e3 - core::option::expect_none_failed::hd1c472dae0b64b95
                                 at /build/rust/src/rustc-1.47.0-src/library/core/src/option.rs:1221
    16:     0x55d3d3183e60 - core::result::Result<T,E>::expect::h230d3e933494e5eb
    17:     0x55d3d3105400 - core::ops::function::FnOnce::call_once::h1cbac506705ba264
    18:     0x55d3d3093e52 - lazy_static::lazy::Lazy<T>::get::{{closure}}::h25c521e55cd942f4
    19:     0x55d3d30c4b3c - std::sync::once::Once::call_once::{{closure}}::h27bd8952c8568e8a
    20:     0x55d3d34a3915 - std::sync::once::Once::call_inner::h493a20e5e46c73ce
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/sync/once.rs:421
    21:     0x55d3d30c4997 - std::sync::once::Once::call_once::hce2dbcce991ae445
    22:     0x55d3d3171449 - <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::h4d9feca36d0d17f3
    23:     0x55d3d31698e8 - bindgen::ensure_libclang_is_loaded::haeea49ad7aa33a97
    24:     0x55d3d3169e9d - bindgen::Bindings::generate::hcbdb5eb24c35e55d
    25:     0x55d3d3167fd4 - bindgen::Builder::generate::hfd6bb4b75720e3f8
    26:     0x55d3d3055008 - build_script_build::main::hefcabf3705312c52
    27:     0x55d3d3052dd3 - core::ops::function::FnOnce::call_once::h9803496d8cafe31d
    28:     0x55d3d3052eb9 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha0e15b687a072b1a
    29:     0x55d3d3052d39 - std::rt::lang_start::{{closure}}::h2cc7ebc3ae03e1ad
    30:     0x55d3d34a6f6e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b46348dde94a3ab
                                 at /build/rust/src/rustc-1.47.0-src/library/core/src/ops/function.rs:259
    31:     0x55d3d34a6f6e - std::panicking::try::do_call::h65a06556d74549bf
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:373
    32:     0x55d3d34a6f6e - std::panicking::try::h906dbc9901f62921
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:337
    33:     0x55d3d34a6f6e - std::panic::catch_unwind::hd56632d711be2855
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/panic.rs:379
    34:     0x55d3d34a6f6e - std::rt::lang_start_internal::h90f188c8b72672f1
                                 at /build/rust/src/rustc-1.47.0-src/library/std/src/rt.rs:51
    35:     0x55d3d3052d18 - std::rt::lang_start::h8679fc3df4ba3c1f
    36:     0x55d3d305513b - main
    37:     0x7f45739ce152 - __libc_start_main
    38:     0x55d3d30520ae - _start
    39:                0x0 - <unknown>
```

rust 1:1.47.0-1
pacman-git 5.2.1.r122.g4d8f58d3-1

Version I tried to compile: 960fb1aa3b4f376659eb7e77da0efb2ad2e58c0a

**Comment by Morganamilo** [comment]
> thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/katt/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.55.1/src/lib.rs:1896:31
  stack backtrace:

Hmm I didn't realize bindgen required libclang. For now, removing the generate feature from the pkgbuild will fix it.

**Comment by kattjevfel** [comment]
That worked, as well did adding clang to makedepends.

**Comment by Morganamilo** [comment]
Removed the generate from the aur pkgbuilds.
